#!/bin/sh

while read file
do
	case "$1" in
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"f")
			convert -flop "$file" "$file" ;;

		"b")
			wallset "$file" ;;
	esac
done
