#!/bin/sh

# graphical applications
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
# export QT_STYLE_OVERRIDE="gtk2"
export QT_QPA_PLATFORMTHEME="qt5ct"
export COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer
exec bspwm
