#!/bin/sh

# run supplied command only if the program is not already running
_run_if() {
	if ! pgrep "$1"; then
		eval "$@"
	fi
}

# set the mouse pointer
xsetroot -cursor_name left_ptr

# load xresources
xrdb "$XDG_CONFIG_HOME/X11/Xresources"

# set wallpaper (wrapper around xwallpaper)
wallset

# numlock
numlockx

# set caps as another escape
setxkbmap -option "caps:escape"

# set both shifts together as caps lock
setxkbmap -option "shift:both_capslock"

# manage keybindings
_run_if sxhkd &

# screen compositor (picom=compton)
_run_if picom &

# lemonbar instance
_run_if panel &

# automatically hide mouse pointer
_run_if unclutter --ignore-scrolling &

# use i3lock as default X screensaver
_run_if xss-lock -l -- i3lock -B 10 -e -n &

_run_if imwheel

# authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# notification daemon
_run_if dunst &

_run_if udiskie -ans &

# system tray
_run_if stalonetray -c "$XDG_CONFIG_HOME/stalonetray/stalonetrayrc" &
