#! /bin/sh
~/.config/bspwm/autostart &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle	 true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4 ## super key
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#3c3836"
bspc config active_border_color "#a89984"
bspc config focused_border_color "#a89984"
bspc config presel_feedback_color "#a89984"

# bspc rule -a Zathura state=tiled
# bspc rule -a Lxappearance state=pseudo_tiled
# bspc rule -a Galculator state=pseudo_tiled
# bspc rule -a vifm-file-chooser state=floating rectangle=800x600+50%+50%
bspc config external_rules_command ~/.config/bspwm/external_rules
